openapi: 3.2.0
info:
  title: PDF Services Create PDF API
  description: "<p><ul>\n\t<li>Learn more about using \n\t<a href=\"https://developer.adobe.com/document-services/docs/overview/pdf-services-api/howtos/api-usage/\"> Adobe PDF Services API.</a>\n\t</li>\n\t<li> Invoking PDF Services API requires an Adobe-provided credential, <a href=\"https://developer.adobe.com/document-services/docs/overview/pdf-services-api/gettingstarted/#step-1--getting-the-access-token\">learn more about authentication.</a>\n\t</li>\n<li><a href=\"https://developer.adobe.com/document-services/docs/overview/pdf-services-api/#sdk\">Downloadable SDKs</a></li>\n<li><a href=\"https://raw.githubusercontent.com/AdobeDocs/pdfservices-api-documentation/main/src/pages/resources/Platform%20PDF%20Services%20Postman%20Collection.zip\" download>Click here</a> to download sample Postman collection</li>\n<li><a href=\"https://raw.githubusercontent.com/AdobeDocs/pdfservices-api-documentation/main/src/pages/resources/Platform%20PDF%20Services%20with%20External%20Storage%20Postman%20Collection.zip\">Click here</a> to download sample Postman collection with External Storage</li><li><a href=\"https://developer.adobe.com/document-services/docs/overview/pdf-services-api/howtos/service-region-configuration-for-apis/\">Click here</a> to know more about <b>multi-region support</b> for PDF Services API</li><li><a href=\"https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK\">Support Forum</a></li><li>First released on 26th September, 2022</li><li>To use your custom external storage, click <a href=\"https://developer.adobe.com/document-services/docs/overview/pdf-services-api/howtos/pdf-external-storage-sol\">here</a>.</li></ul></p>"
  version: ''
servers:
- url: https://pdf-services-ue1.adobe.io
- url: https://pdf-services-ew1.adobe.io
tags:
- name: Create PDF
  description: Create PDF document from Microsoft Office documents (Word, Excel and PowerPoint), Markdown and Image file formats.
paths:
  /operation/createpdf:
    post:
      tags:
      - Create PDF
      summary: Create PDF document from non PDF document.
      description: Create PDF document from Microsoft Office documents (Word, Excel and PowerPoint), Markdown and Image file formats.
      operationId: pdfoperations.createpdf
      parameters:
      - name: Authorization
        in: header
        description: Bearer + Token (<a href="https://developer.adobe.com/document-services/docs/overview/pdf-services-api/gettingstarted/#step-1--getting-the-access-token">Learn more</a> about getting the access token)
        required: true
        schema:
          type: string
      - name: x-api-key
        in: header
        description: The clientId from the generated credentials
        required: true
        schema:
          type: string
      requestBody:
        description: Params for Create PDF Operation. Refer to the External Section below for using external storage with Create PDF Operation.
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/CreatePDFInternal'
              - $ref: '#/components/schemas/CreatePDFExternal'
        required: true
      responses:
        '201':
          description: Request creation for the operation and status uri generated, which can be found in the 'location' header.
          headers:
            location:
              description: Job status URI for polling the results
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
        '400':
          description: Bad Request. The request was invalid or cannot be otherwise served.
          headers:
            content-type:
              description: The content type of the POST API call response
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '404':
          description: Resource Not Found.
          headers:
            content-type:
              description: The content type of the POST API call response
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        '401':
          description: Unauthorized.
          headers:
            content-type:
              description: The content type of the error JSON response.
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '429':
          description: Caller doesn't have sufficient quota for this operation.
          headers:
            content-type:
              description: The content type of the POST API call response
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/429'
        '500':
          description: Internal Server Error. The server has encountered an error and is unable to process your request at this time.
          headers:
            content-type:
              description: The content type of the POST API call response
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'
      x-codegen-request-body-name: body
  /operation/createpdf/{jobID}/status:
    get:
      tags:
      - Create PDF
      summary: Poll the create PDF job for completion
      operationId: pdfoperations.jobstatus
      parameters:
      - name: jobID
        in: path
        description: Job ID of the request
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: Bearer + Token (<a href="https://developer.adobe.com/document-services/docs/overview/pdf-services-api/gettingstarted/#step-1--getting-the-access-token">Learn more</a> about getting the access token)
        required: true
        schema:
          type: string
      - name: x-api-key
        in: header
        description: The clientId from the generated credentials
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A response with job information.
          headers:
            content-type:
              description: The content type of the status call response.
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePDFJobStatus'
        '400':
          description: Bad Request. The request was invalid or cannot be otherwise served.
          headers:
            content-type:
              description: The content type of the status call response
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status400'
        '404':
          description: Resource Not Found.
          headers:
            content-type:
              description: The content type of the POST API call response
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Satus404'
        '401':
          description: Unauthorized.
          headers:
            content-type:
              description: The content type of the POST API call response
              schema:
                type: string
            x-server:
              description: The name and version of the server.
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Satus401'
        '429':
          description: Caller doesn't have sufficient quota for this operation.
          headers:
            content-type:
              description: The content type of the POST API call response
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Satus429'
        '500':
          description: Internal Server Error. The server has encountered an error and is unable to process your request at this time.
          headers:
            content-type:
              description: The content type of the POST API call response
              schema:
                type: string
            x-request-id:
              description: A unique value to identify this request. If x-request-id is specified in the POST request, this value will be the same as the input.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Satus500'
components:
  schemas:
    done:
      title: done
      oneOf:
      - $ref: '#/components/schemas/internal'
      - $ref: '#/components/schemas/externalstatus'
    Satus404:
      properties:
        error:
          type: object
          properties:
            code:
              description: The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific.
              type: string
            message:
              description: "An English language string that contains more information about the error.  \n\n<table><tr><th>code</th><th>message</th></tr><tr><td>NOT_FOUND</td><td>Job not found.</td></tr></table>"
              type: string
      example:
        error:
          code: NOT_FOUND
          message: Job not found.
    '400':
      properties:
        error:
          type: object
          properties:
            code:
              description: The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific.
              type: string
            message:
              description: "An English language string that contains more information about the error. \n\n<table><tr><th>code</th><th>message</th></tr><tr><td>BAD_REQUEST</td><td>Bad Request.</td></tr></table>"
              type: string
      example:
        error:
          code: BAD_REQUEST
          message: Bad Request.
    '500':
      properties:
        error:
          type: object
          properties:
            code:
              description: The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific.
              type: string
            message:
              description: "An English language string that contains more information about the error.  \n\n<table><tr><th>code</th><th>message</th></tr><tr><td>INTERNAL_SERVER_ERROR</td><td>There was an error processing your request.</td></tr><tr><td>UNKNOWN</td><td>Unknown error.</td></tr></table>"
              type: string
      example:
        error:
          code: INTERNAL_SERVER_ERROR
          message: There was an error processing your request.
    external:
      title: External with an output URI in the request
      description: Response in case of 'done' status using signed urls
      type: object
      properties:
        status:
          description: Job Status
          type: string
          enum:
          - done
      example:
        status: done
    externaldonewithoutoutput:
      title: External without an output URI in the request
      description: Response in case of 'done' status
      type: object
      properties:
        status:
          description: Job Status
          type: string
          enum:
          - done
        asset:
          $ref: '#/components/schemas/responseAsset'
      example:
        status: done
        asset:
          metadata:
            type: application/pdf
            size: 200791
          downloadUri: https://dcplatformstorageservice-dev-us-east-1.s3-accelerate.amazonaws.com/6bb12fd8-3233-4340-916b-4835917857be?X-Amz-Security-Token=FwoGZXIvYXdzEE0aDOLg7PFwVB1bjEMxQCLTAe3pjf%2Fgl2Pj%2FcjOaY%2BHfduju9SXTp1Pn8C4GapIXm%2F8tuR4cGPYGC0goU21qZxCq9R%2F8z2bOmB2EL%2BZrhbPLbaNcpzf5Vud%2B3Bmn61MEJiBdU%2BhZqasX5YhVxdnzhfpl5KfKeq2kwROVMqJcyHGdxw5h0%2Bi0sD2I8sqkbPmnBi0WOtYNwz7TQq42oe8W5KYHpq6WMya9OQgx0u7qg0inYwBnQu5UQ9NJJQY2MSU11IuZ0uE%2B%2FNAPuq3VfEIn3txK%2FFfIxGz9%2BInehhHroKjBFULzy0olY2rlwYyLQDwHHr2eyuy%2BaoGVaq%2BSUNH8T0OKIicbbZfQ5wjF0hK2FzVXwfebtDG4qq%2BiA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220803T190422Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=REDACTED_AWS_ACCESS_KEY_ID%2F20220803%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5d8c3f421c68c009b4471919a319ba460495c72afe51674d23266bc124fe9a56
          assetID: urn:aaid:AS:UE1:23c30ee0-2c4d-46d6-87f2-087832fca718
    '404':
      properties:
        error:
          type: object
          properties:
            code:
              description: The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific.
              type: string
            message:
              description: "An English language string that contains more information about the error. \n\n<table><tr><th>code</th><th>message</th></tr><tr><td>NOT_FOUND</td><td>Asset not found.</td></tr></table>"
              type: string
      example:
        error:
          code: NOT_FOUND
          message: Asset not found.
    ExternalStorageInput:
      title: Input
      description: Params representing input object.
      type: object
      properties:
        uri:
          description: Input file Download Signed URI.
          type: string
        storage:
          description: Specifies the type of the external storage
          type: string
          enum:
          - S3
          - SHAREPOINT
          - DROPBOX
          - BLOB
      required:
      - uri
    CreatePDFPageRange:
      title: pageRange
      description: Parameters to allow specifying which pages to be included for the PDF document. If pageRange is not provided, all pages are considered by default.
      type: object
      properties:
        start:
          description: Start page of this page range. Page numbers are indexed from 1 to N.
          type: number
        end:
          description: End page of this page range. Page numbers are indexed from 1 to N.
          type: number
    CreatePDFJobStatus:
      oneOf:
      - $ref: '#/components/schemas/inprogress'
      - $ref: '#/components/schemas/done'
      - $ref: '#/components/schemas/failed'
    CreatePDFExternal:
      title: External
      description: Params for Create PDF Operation using external storage
      type: object
      properties:
        input:
          $ref: '#/components/schemas/ExternalStorageInput'
        output:
          $ref: '#/components/schemas/ExternalStorageOutput'
        params:
          description: Params for Create PDF processing
          type: object
          properties:
            documentLanguage:
              $ref: '#/components/schemas/documentLanguage'
        notifiers:
          $ref: '#/components/schemas/notifiers'
      default:
        documentLanguage: en-US
      example:
        input:
          uri: https://dcplatformstorageservice-dev-us-east-1.s3-accelerate.amazonaws.com/dc-platformService-automation_dc-platformService-automation%40AdobeID/f378b68a-7427-40a7-9d6f-5ec804bf3a0f?X-Amz-Security-Token=FwoGZXIvYXdzEIL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDEIZGjPptSLXfARH1yLTAfJTaRdY3uk3U6cPXeYmRyehW9X7CHlzsGvTlLmJTmfNjAMgEEup0IDFWMZoem2JY%2BGO5Bdn%2FJU%2FhdKbc6%2FNmOAHAcAcY0%2F5h1kMempmrqwJvwRkfU%2BQi0JEz1Bj6QBaV3%2B9mluSmL7OuNgCmVtzPVJD3ilIncP42hY8P6zd86AMtN9Y7l5hfHvGzJJdQSB5jsF3NdAONhBIj21hJO2yTVjuSZZh%2FPteHH4C2n7GtxPqvWKz5%2FOAj2GgmoMNN%2BTDzyyT1Vq29%2BtLwsWWveMKPdxD0Nwo2eK%2BpQYyLTokOdaY01RJkdMmYzGhPO6%2FLriOy4k0zXz5IBARU3snKFzRQbyo%2Fumb2CaGZg%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230713T081101Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=REDACTED_AWS_ACCESS_KEY_ID%2F20230713%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=2f9038878059237c1a149139e4addda4bfdabeb5868da3e4ad29ad4f8395b47a
          storage: S3
        output:
          uri: https://dcplatformstorageservice-dev-us-east-1.s3-accelerate.amazonaws.com/dc-platformService-automation_dc-platformService-automation%40AdobeID/6c87e993-5359-497a-8580-994cc87af336?X-Amz-Security-Token=FwoGZXIvYXdzEIL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDPeFWZ0VRI3WwhzPpyLTAf9IHH25%2BhV1x17SRxzjCIepHKWnI3V9nmM5qu5mru9ud2iyJ3p9JEn%2Bu%2Fa6YWRx9EsoTbKoTJAWGi7WfDqHjn5y3nophcNveAMS7FnWLogK43GBvl4IIMLxbC5dMRcfqlsCw8%2FHcTep2bgGIv0xjvK4BirN6qa9rnyr0aBGB8sdxAxagx6zfaZ1f6bV4YcbEx2qQIXEaQAgfy0Oo%2BY9wUxTThHrO33PVTWpJ6Zhy%2FokJ3eETa551zc9xevZUqtEpvu41vmmMZeWyBidwbYCNG790t0oh%2BK%2BpQYyLTrNKbZU%2B%2Bf7i5NHcj50bZWHbEZrHD03psMAToKLsxSpnbrN8PtJsIZ8zddP9A%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230713T081108Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=3599&X-Amz-Credential=REDACTED_AWS_ACCESS_KEY_ID%2F20230713%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=158407c206615682fbf562786011297b258464221de3a715a7ea389db1560846
          storage: S3
        params:
          documentLanguage: en-US
          pageRange:
            start: 1
            end: 4
        notifiers:
        - type: CALLBACK
          data:
            url: https://dummy.callback.org/
            headers:
              x-api-key: dummykey
              access-token: dummytoken
      required:
      - input
      additionalProperties: false
    failed:
      description: Response in case of 'failed' status
      type: object
      properties:
        status:
          description: Job Status
          type: string
          enum:
          - failed
        error:
          type: object
          properties:
            status:
              description: Http status code returned by the service
              type: integer
            code:
              description: The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific.
              type: string
            message:
              description: "An English language string that contains more information about the error. \n\n<table><tr><th>status</th><th>code</th><th>message</th></tr><tr><td>400</td><td>CORRUPT_DOCUMENT</td><td>For $(format) mime-type The input file appears to be corrupted and cannot be processed.</td></tr><tr><td>400</td><td>PASSWORD_PROTECTED</td><td>Source file is protected and cannot be processed.</td></tr><tr><td>500</td><td>INTERNAL_SERVER_ERROR</td><td>There was an error processing your request.</td></tr></table>"
              type: string
      example:
        status: failed
        error:
          status: 500
          code: INTERNAL_SERVER_ERROR
          message: There was an error processing your request
    externalstatus:
      title: External
      oneOf:
      - $ref: '#/components/schemas/externaldonewithoutoutput'
      - $ref: '#/components/schemas/external'
    ExternalStorageOutput:
      title: Output
      description: Params representing output object
      type: object
      properties:
        uri:
          description: Output file Upload Signed URI.
          type: string
        storage:
          description: Specifies the type of the external storage
          type: string
          enum:
          - S3
          - SHAREPOINT
          - DROPBOX
          - BLOB
    '429':
      properties:
        error:
          type: object
          properties:
            code:
              description: The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific.
              type: string
            message:
              description: "An English language string that contains more information about the error.  \n\n<table><tr><th>code</th><th>message</th></tr><tr><td>TOO_MANY_REQUESTS</td><td>Too Many Requests.</td></tr><tr><td>INSUFFICIENT_QUOTA</td><td>Either Quota for this operation is not available or Free trial quota is exhausted. Please visit (www.adobe.com/go/pdftoolsapi_home) to start using free trial quota or (www.adobe.com/go/pdftoolsapi_err_quota) to upgrade to paid credentials.</td></tr></table>"
              type: string
      example:
        error:
          code: TOO_MANY_REQUESTS
          message: Too Many Requests.
    Status400:
      properties:
        error:
          type: object
          properties:
            code:
              description: The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific.
              type: string
            message:
              description: "An English language string that contains more information about the error.  \n\n<table><tr><th>code</th><th>message</th></tr><tr><td>INVALID_JOB_ID</td><td>Invalid job id present in path param.</td></tr></table>"
              type: string
      example:
        error:
          code: INVALID_JOB_ID
          message: Invalid job id present in path param.
    inprogress:
      description: Response in case of 'in progress' status
      type: object
      properties:
        status:
          description: Job Status
          type: string
          enum:
          - in progress
      example:
        status: in progress
    documentLanguage:
      description: "Specifies the default language for the input non-PDF document. In absence of font info within file’s content, an appropriate font is chosen on its basis. \n\n Note : ja-JP Locale is currently not supported in EU region. "
      type: string
      default: en-US
      enum:
      - ca-ES
      - cs-CZ
      - da-DK
      - de-DE
      - en-AE
      - en-GB
      - en-IL
      - en-US
      - es-ES
      - es-MX
      - eu-ES
      - fi-FI
      - fr-CA
      - fr-FR
      - fr-MA
      - hr-HR
      - ht-HU
      - it-IT
      - ja-JP
      - ko-KR
      - nb-NO
      - nl-NL
      - pl-PL
      - pt-BR
      - pt-PT
      - ro-RO
      - ru-RU
      - sk-SK
      - sl-SI
      - sv-SE
      - tr-TR
      - uk-UA
      - zh-CN
      - zh-TW
      - lt-LT
      - el-GR
      - zh-HK
      - hu-HU
      - et-EE
      - lv-LV
      - bg-BG
      - mt-MT
      - sr-SR
      - ca-CA
      - mk-MK
      - de-CH
      - no-NO
      - iw-IL
    responseAsset:
      title: asset
      description: Details of output asset document. For more details <a href = 'https://developer.adobe.com/document-services/docs/apis/#tag/Assets'> click here </a>.
      type: object
      properties:
        metadata:
          type: object
          description: metadata details of output asset.
          properties:
            size:
              description: The size of the Resource in bytes. This value helps in making range requests.
              type: integer
            type:
              description: The media type of the Resource.
              type: string
        assetID:
          description: An asset ID identifying an asset that is globally unique and never reused.
          type: string
          required: false
        downloadUri:
          description: The URL used to download the Resource directly to the cloud provider.
          type: string
      example:
        status: done
        asset:
          metadata:
            type: application/pdf
            size: 200791
          downloadUri: https://dcplatformstorageservice-dev-us-east-1.s3-accelerate.amazonaws.com/6bb12fd8-3233-4340-916b-4835917857be?X-Amz-Security-Token=FwoGZXIvYXdzEE0aDOLg7PFwVB1bjEMxQCLTAe3pjf%2Fgl2Pj%2FcjOaY%2BHfduju9SXTp1Pn8C4GapIXm%2F8tuR4cGPYGC0goU21qZxCq9R%2F8z2bOmB2EL%2BZrhbPLbaNcpzf5Vud%2B3Bmn61MEJiBdU%2BhZqasX5YhVxdnzhfpl5KfKeq2kwROVMqJcyHGdxw5h0%2Bi0sD2I8sqkbPmnBi0WOtYNwz7TQq42oe8W5KYHpq6WMya9OQgx0u7qg0inYwBnQu5UQ9NJJQY2MSU11IuZ0uE%2B%2FNAPuq3VfEIn3txK%2FFfIxGz9%2BInehhHroKjBFULzy0olY2rlwYyLQDwHHr2eyuy%2BaoGVaq%2BSUNH8T0OKIicbbZfQ5wjF0hK2FzVXwfebtDG4qq%2BiA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220803T190422Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=REDACTED_AWS_ACCESS_KEY_ID%2F20220803%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5d8c3f421c68c009b4471919a319ba460495c72afe51674d23266bc124fe9a56
          assetID: urn:aaid:AS:UE1:23c30ee0-2c4d-46d6-87f2-087832fca718
    CreatePDFInternal:
      title: Internal
      description: Params for Create PDF Operation
      type: object
      properties:
        assetID:
          description: A file assetID. Supported file formats are bmp, doc, docx, gif, jpeg, jpg, png, ppt, pptx, rtf, tif, tiff, txt, xls, xlsx and md. For more details <a href = 'https://developer.adobe.com/document-services/docs/apis/#tag/Assets'> click here </a>.
          type: string
        documentLanguage:
          $ref: '#/components/schemas/documentLanguage'
        isActiveSheetConversion:
          description: Specifies whether to convert only the active sheet of the Excel file.
          type: boolean
          default: false
        pageRange:
          $ref: '#/components/schemas/CreatePDFPageRange'
        notifiers:
          $ref: '#/components/schemas/notifiers'
      default:
        documentLanguage: en-US
      example:
        assetID: urn:aaid:AS:UE1:23c30ee0-2c4d-46d6-87f2-087832fca718
        documentLanguage: en-US
        pageRange:
          start: 1
          end: 4
        notifiers:
        - type: CALLBACK
          data:
            url: https://dummy.callback.org/
            headers:
              x-api-key: dummykey
              access-token: dummytoken
      required:
      - assetID
      additionalProperties: false
    Satus429:
      properties:
        error_code:
          description: 'The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific. '
          type: string
        message:
          description: "An English language string that contains more information about the error. \n\n<table><tr><th>code</th><th>message</th></tr><tr><td>429001</td><td>Service usage limit reached</td></tr><tr><td>429002</td><td>Developer key usage limit reached</td></tr><tr><td>429050</td><td>Too many requests</td></tr></table>"
          type: string
      example:
        error_code: '429050'
        message: Too many requests
    notifiers:
      description: Specifies the notifiers to be invoked on the completion of job. To know more about notifiers, please see the <a href="https://developer.adobe.com/document-services/docs/overview/pdf-services-api/howtos/webhook-notification/">documentation</a>.
      type: array
      items:
        properties:
          type:
            description: Specifies the notifier type. Currently supported value is "CALLBACK" only.
            type: string
          data:
            description: Specifies the data needed to invoke the notifier.
            type: object
        required:
        - type
        - data
    Satus401:
      properties:
        error:
          type: object
          properties:
            code:
              description: The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific.
              type: string
            message:
              description: "An English language string that contains more information about the error.  \n\n<table><tr><th>code</th><th>message</th></tr><tr><td>UNAUTHORIZED</td><td>Not authorised to perform the operation.</td></tr></table>"
              type: string
      example:
        error:
          code: UNAUTHORIZED
          message: Not authorised to perform the operation.
    '401':
      properties:
        error:
          type: object
          properties:
            code:
              description: The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific.
              type: string
            message:
              description: "An English language string that contains more information about the error.  \n\n<table><tr><th>code</th><th>message</th></tr><tr><td>UNAUTHORIZED</td><td>Not authorised to perform the operation.</td></tr></table>"
              type: string
      example:
        error:
          code: UNAUTHORIZED
          message: Not authorised to perform the operation.
    internal:
      title: Internal
      description: Response in case of 'done' status
      type: object
      properties:
        status:
          description: Job Status
          type: string
          enum:
          - done
        asset:
          $ref: '#/components/schemas/responseAsset'
      example:
        status: done
        asset:
          metadata:
            type: application/pdf
            size: 200791
          downloadUri: https://dcplatformstorageservice-dev-us-east-1.s3-accelerate.amazonaws.com/6bb12fd8-3233-4340-916b-4835917857be?X-Amz-Security-Token=FwoGZXIvYXdzEE0aDOLg7PFwVB1bjEMxQCLTAe3pjf%2Fgl2Pj%2FcjOaY%2BHfduju9SXTp1Pn8C4GapIXm%2F8tuR4cGPYGC0goU21qZxCq9R%2F8z2bOmB2EL%2BZrhbPLbaNcpzf5Vud%2B3Bmn61MEJiBdU%2BhZqasX5YhVxdnzhfpl5KfKeq2kwROVMqJcyHGdxw5h0%2Bi0sD2I8sqkbPmnBi0WOtYNwz7TQq42oe8W5KYHpq6WMya9OQgx0u7qg0inYwBnQu5UQ9NJJQY2MSU11IuZ0uE%2B%2FNAPuq3VfEIn3txK%2FFfIxGz9%2BInehhHroKjBFULzy0olY2rlwYyLQDwHHr2eyuy%2BaoGVaq%2BSUNH8T0OKIicbbZfQ5wjF0hK2FzVXwfebtDG4qq%2BiA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220803T190422Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=REDACTED_AWS_ACCESS_KEY_ID%2F20220803%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5d8c3f421c68c009b4471919a319ba460495c72afe51674d23266bc124fe9a56
          assetID: urn:aaid:AS:UE1:23c30ee0-2c4d-46d6-87f2-087832fca718
    Satus500:
      properties:
        error:
          type: object
          properties:
            code:
              description: The string containing the code field. code is the Mnemonic returned by service in case of any failure. The below list is extendable and going forward the error codes can become more specific.
              type: string
            message:
              description: "An English language string that contains more information about the error. \n\n<table><tr><th>code</th><th>message</th></tr><tr><td>INTERNAL_SERVER_ERROR</td><td>There was an error processing your request.</td></tr><tr><td>UNKNOWN</td><td>Unknown error.</td></tr></table>"
              type: string
      example:
        error:
          code: INTERNAL_SERVER_ERROR
          message: There was an error processing your request.
x-tagGroups:
- name: Authentication
  tags:
  - Generate Token
- name: Files
  tags:
  - Assets
- name: PDF Operations
  tags:
  - Combine PDF
  - Compress PDF
  - Create PDF
  - Document Generation
  - Export PDF
  - Export PDF Form Data
  - Extract PDF
  - Html to PDF
  - Import PDF Form Data
  - Linearize PDF
  - OCR
  - Page Manipulation
  - PDF Accessibility Auto-Tag
  - PDF Accessibility Checker
  - PDF Electronic Seal
  - PDF Properties
  - PDF To Images
  - PDF To Markdown
  - PDF Watermark
  - Protect PDF
  - Remove Protection
  - Split PDF
